resource_types:
  - name: irc-notification
    type: docker-image
    source:
      repository: flavorjones/irc-notification-resource


resources:
  - name: ci
    type: git
    source:
      uri: https://github.com/flavorjones/irc-notification-resource/
      branch: master
      disable_ci_skip: true # always get the latest pipeline configuration
  - name: irc-notification-resource
    type: git
    source:
      uri: https://github.com/flavorjones/irc-notification-resource/
      branch: master
      ignore_paths:
        - ci/**
  - name: "freenode #random"
    type: irc-notification
    source:
      server: chat.freenode.net
      port: 7070
      channel: "#random"
      user: ((nokobot-irc-username))
      password: ((nokobot-irc-password))
      usetls: true
      join: true
      debug: true # danger, make sure the job is private

jobs:
  - name: master
    public: true
    plan:
      - get: ci
      - get: irc-notification-resource
        trigger: true
      - task: make-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: "flavorjones/irc-notification-resource", tag: "test" }
          inputs:
            - name: ci
            - name: irc-notification-resource
          run:
            path: ci/ci/tasks/make-test/run.sh

  - name: test-notification
    public: false # needs to be private because debug messages contain the password
    plan:
      - put: "freenode #random"
        params:
          message: "This is a test."
